name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: First Step - display first name
        run: echo "Hello World"
      - name: Second Step
        run: |
          npm -v
          node -v