name: Second Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Command in Multiline
        run: |
          pwd
          ls -a
          uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}