name: Second Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: List file and copy repo
        run: ls -a
      - uses: actions/checkout@v5
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls -a